-- MySQL Script generated by MySQL Workbench
-- Sat Nov 11 16:57:00 2017
-- Model: Equipe374876  Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Triggers
-- -----------------------------------------------------
DELIMITER $$

USE `Equipe374876`$$
DROP TRIGGER IF EXISTS `salario_1500_bef_ins` $$
USE `Equipe374876`$$
CREATE DEFINER = CURRENT_USER TRIGGER `Equipe374876`.`salario_1500_bef_ins` BEFORE INSERT ON `funcionario` FOR EACH ROW
BEGIN
	IF NEW.salario < 1500.00 THEN
		SIGNAL SQLSTATE'45000' SET MESSAGE_TEXT = 'O salário não pode ser menor que R$1500,00!';
    END IF;
END;$$


USE `Equipe374876`$$
DROP TRIGGER IF EXISTS `salario_montante_aft_ins` $$
USE `Equipe374876`$$
CREATE DEFINER = CURRENT_USER TRIGGER `Equipe374876`.`salario_montante_aft_ins` AFTER INSERT ON `funcionario` FOR EACH ROW
BEGIN
	UPDATE agencia a 
	SET a.salario_montante = (SELECT 
			SUM(f.salario)
		FROM
			funcionario f
		GROUP BY f.lotacao
		HAVING f.lotacao = NEW.lotacao)
	WHERE
		a.numero = NEW.lotacao;
END;$$


USE `Equipe374876`$$
DROP TRIGGER IF EXISTS `salario_1500_bef_upd` $$
USE `Equipe374876`$$
CREATE DEFINER = CURRENT_USER TRIGGER `Equipe374876`.`salario_1500_bef_upd` BEFORE UPDATE ON `funcionario` FOR EACH ROW
BEGIN
	IF NEW.salario < 1500.00 THEN
		SIGNAL SQLSTATE'45000' SET MESSAGE_TEXT = 'O salário não pode ser menor que R$1500,00!';
    END IF;
END;$$


USE `Equipe374876`$$
DROP TRIGGER IF EXISTS `salario_montante_aft_upd` $$
USE `Equipe374876`$$
CREATE DEFINER = CURRENT_USER TRIGGER `Equipe374876`.`salario_montante_aft_upd` AFTER UPDATE ON `funcionario` FOR EACH ROW
BEGIN
	UPDATE agencia a 
	SET a.salario_montante = (SELECT 
			SUM(f.salario)
		FROM
			funcionario f
		GROUP BY f.lotacao
		HAVING f.lotacao = NEW.lotacao)
	WHERE
		a.numero = NEW.lotacao;
END;$$


USE `Equipe374876`$$
DROP TRIGGER IF EXISTS `salario_montante_aft_del` $$
USE `Equipe374876`$$
CREATE DEFINER = CURRENT_USER TRIGGER `Equipe374876`.`salario_montante_aft_del` AFTER DELETE ON `funcionario` FOR EACH ROW
BEGIN
	UPDATE agencia a 
	SET a.salario_montante = (SELECT 
			SUM(f.salario)
		FROM
			funcionario f
		GROUP BY f.lotacao
		HAVING f.lotacao = OLD.lotacao)
	WHERE
		a.numero = OLD.lotacao;
END;$$


USE `Equipe374876`$$
DROP TRIGGER IF EXISTS `cinco_dependentes_bef_ins` $$
USE `Equipe374876`$$
CREATE DEFINER = CURRENT_USER TRIGGER `Equipe374876`.`cinco_dependentes_bef_ins` BEFORE INSERT ON `dependente` FOR EACH ROW
BEGIN
	IF (SELECT COUNT(d.mat_funcionario) FROM funcionario f JOIN dependente d ON d.mat_funcionario = f.matricula WHERE d.mat_funcionario = NEW.mat_funcionario) = 5 THEN
		SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Este funcionario já possui cinco dependentes!';
    END IF;
END;$$


DELIMITER ;