-- MySQL Script generated by MySQL Workbench
-- Wed Nov  8 20:32:23 2017
-- Model: Equipe374876  Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Equipe374876
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Equipe374876` ;

-- -----------------------------------------------------
-- Schema Equipe374876
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Equipe374876` DEFAULT CHARACTER SET utf8 ;
USE `Equipe374876` ;

-- -----------------------------------------------------
-- Table `funcionario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `funcionario` ;

CREATE TABLE IF NOT EXISTS `funcionario` (
  `matricula` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `sexo` ENUM('Feminino', 'Masculino') NOT NULL,
  `data_nasc` DATE NOT NULL,
  `cidade` VARCHAR(45) NULL,
  `endereco` VARCHAR(45) NULL,
  `cargo` ENUM('Atendente', 'Caixa', 'Gerente') NOT NULL,
  `salario` DECIMAL(8,2) NOT NULL DEFAULT 0.00,
  `senha` VARCHAR(20) NOT NULL,
  `lotacao` INT NOT NULL,
  PRIMARY KEY (`matricula`),
  INDEX `fk_Funcionario_Agencia_idx` (`lotacao` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `agencia` ;

CREATE TABLE IF NOT EXISTS `agencia` (
  `numero` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `mat_gerente` INT NOT NULL,
  `salario_montante` DECIMAL(12,2) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`numero`),
  INDEX `fk_Agencia_Funcionario1_idx` (`mat_gerente` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `conta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conta` ;

CREATE TABLE IF NOT EXISTS `conta` (
  `num_conta` INT NOT NULL AUTO_INCREMENT,
  `num_agencia` INT NOT NULL,
  `saldo` DECIMAL(11,2) NOT NULL DEFAULT 0.00,
  `senha` INT(6) NOT NULL,
  PRIMARY KEY (`num_conta`),
  INDEX `fk_Contas_Agencia1_idx` (`num_agencia` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `conta_poupanca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conta_poupanca` ;

CREATE TABLE IF NOT EXISTS `conta_poupanca` (
  `num_conta` INT NOT NULL,
  `taxa_juros` DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  INDEX `fk_Poupança_Contas1_idx` (`num_conta` ASC),
  PRIMARY KEY (`num_conta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `conta_especial`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conta_especial` ;

CREATE TABLE IF NOT EXISTS `conta_especial` (
  `num_conta` INT NOT NULL,
  `limite_credito` DECIMAL(7,2) NOT NULL DEFAULT 0.00,
  INDEX `fk_Conta especial_Contas1_idx` (`num_conta` ASC),
  PRIMARY KEY (`num_conta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `transacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `transacao` ;

CREATE TABLE IF NOT EXISTS `transacao` (
  `num_transacao` INT NOT NULL AUTO_INCREMENT,
  `valor_transacao` DECIMAL(10,2) NOT NULL,
  `data_hora` DATETIME NOT NULL,
  `tipo` ENUM('Saque', 'Estorno', 'Transferência', 'Depósito') NOT NULL,
  PRIMARY KEY (`num_transacao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `realiza`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `realiza` ;

CREATE TABLE IF NOT EXISTS `realiza` (
  `num_transacao` INT NOT NULL,
  `num_conta` INT NOT NULL,
  PRIMARY KEY (`num_transacao`, `num_conta`),
  INDEX `fk_Transacoes_has_Contas_Contas1_idx` (`num_conta` ASC),
  INDEX `fk_Transacoes_has_Contas_Transacoes1_idx` (`num_transacao` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cliente` ;

CREATE TABLE IF NOT EXISTS `cliente` (
  `cpf` CHAR(11) NOT NULL,
  `rg` VARCHAR(25) NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `data_nasc` DATE NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cpf`),
  UNIQUE INDEX `RG_UNIQUE` (`rg` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `conta_cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conta_cliente` ;

CREATE TABLE IF NOT EXISTS `conta_cliente` (
  `cpf_cliente` CHAR(11) NOT NULL,
  `num_conta` INT NOT NULL,
  `num_agencia` INT NOT NULL,
  INDEX `fk_Cliente-Conta_Clientes1_idx` (`cpf_cliente` ASC),
  INDEX `fk_Cliente-Conta_Contas1_idx` (`num_conta` ASC),
  INDEX `fk_Cliente-Conta_agencia1_idx` (`num_agencia` ASC),
  PRIMARY KEY (`cpf_cliente`, `num_conta`, `num_agencia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dependente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `dependente` ;

CREATE TABLE IF NOT EXISTS `dependente` (
  `mat_funcionario` INT NOT NULL,
  `nome_dependente` VARCHAR(50) NOT NULL,
  `parentesco` ENUM('Filho', 'Cônjuge', 'Genitor') NOT NULL,
  `data_nasc` DATE NOT NULL,
  `idade` INT NULL,
  PRIMARY KEY (`mat_funcionario`, `nome_dependente`),
  INDEX `fk_Dependente_Funcionario1_idx` (`mat_funcionario` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `conta_corrente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `conta_corrente` ;

CREATE TABLE IF NOT EXISTS `conta_corrente` (
  `num_conta` INT NOT NULL,
  PRIMARY KEY (`num_conta`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;